spring:
    application:
        name: AdoptionAndBreedingModule

    rabbitmq:
        host: ${RABBITMQ_HOST}
        port: ${RABBITMQ_PORT}
        username: ${RABBITMQ_USERNAME}
        password: ${RABBITMQ_PASSWORD}

    super:
        admin:
            username: ${SUPER_ADMIN_USERNAME}

    datasource:
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        url: ${ADOPTION_DB_URL}

    flyway:
        enabled: true
        locations: classpath:db/migration
        baseline-on-migrate: true

    jpa:
        hibernate:
            ddl-auto: none
        #        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true

    security:
        user:
            name: ${SECURITY_USER_NAME}
            password: ${SECURITY_USER_PASSWORD}
    jwt:
        secret-key: ${SPRING_JWT_SECRET_KEY}

feed:
    weights:
        recency: 0.4
        totalReacts: 0.3
        petCategoryAffinity: 0.25
        postCategoryAffinity: 0.2
    freshness-window-hours: 96

server:
    port: ${ADOPTION_SERVER_PORT}
    error:
        include-message: always
        include-binding-errors: always

logging:
    level:
        org.springframework.cache: DEBUG
        org.springframework.data.redis.cache: DEBUG
        org.springframework.security: DEBUG
        org.springframework.web.servlet.DispatcherServlet: DEBUG