spring:
    application:
        name: AdoptionAndBreedingModule

    rabbitmq:
        host: rabbitmq
        port: 5672
        username: guest
        password: guest

    datasource:
        url: jdbc:postgresql://postgres:5432/adoption_breeding
        username: postgres
        password: admin

    jpa:
        hibernate:
            ddl-auto: update
        #        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true

    security:
        user:
            name: admin
            password: 1234
    jwt:
        secret-key: 4ioX3ogCr4GAZ9gB99txf1LyhqVOmTJ8RsL9hyJzZXQ=

feed:
    weights:
        recency:              400
        totalReacts:          300
        petCategoryAffinity:  250
        postCategoryAffinity: 200
        friendBoost:          5000
        followeeBoost:        3000
        distance:             400
    freshness-window-hours: 96

post:
  expiration-days: 45

server:
    port: 8082
    error:
        include-message: always
        include-binding-errors: always

logging:
    level:
        org.springframework.cache: DEBUG
        org.springframework.data.redis.cache: DEBUG
        org.springframework.security: DEBUG
        org.springframework.web.servlet.DispatcherServlet: DEBUG
