spring:
  application:
    name: AdoptionAndBreedingModule

  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest

  data:
    redis:
      host: localhost
      port: 6379

  super:
    admin:
      username: superadmin

  datasource:
    username: development
    password: development
    url: jdbc:postgresql://localhost:5433/adoption_breeding_dev

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: none
    #        show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    user:
      name: admin
      password: 1234

  jwt:
    secret-key: 5uaW4pgDs9KTX3rB99jvF7WyusLOnPA7DyM3gyRkZXQ9=

feed:
  weights:
    recency: 0.4
    totalReacts: 0.3
    petCategoryAffinity: 0.25
    postCategoryAffinity: 0.2
  freshness-window-hours: 96

server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.data.redis.cache: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG